//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTracking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrackerEntities : DbContext
    {
        public TrackerEntities()
            : base("name=TrackerEntities")
        {
            //this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Box> Box { get; set; }
        public virtual DbSet<Gate> Gate { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Track> Track { get; set; }
        public virtual DbSet<TrackedItem> TrackedItem { get; set; }
        public virtual DbSet<TrackHistory> TrackHistory { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
