//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackHistory
    {
        public int ID { get; set; }
        public int TrackID { get; set; }
        public Nullable<int> GateID { get; set; }
        public System.DateTime ScanTime { get; set; }

        [System.Runtime.Serialization.IgnoreDataMember]
        public virtual Gate Gate { get; set; }
        [System.Runtime.Serialization.IgnoreDataMember]
        public virtual Track Track { get; set; }
    }
}
