//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Track()
        {
            this.TrackedItem = new HashSet<TrackedItem>();
            this.TrackHistory = new HashSet<TrackHistory>();
        }
    
        public int ID { get; set; }
        public int BoxID { get; set; }
        public int GateID { get; set; }
        public int UserID { get; set; }
        public byte Status { get; set; }

        [System.Runtime.Serialization.IgnoreDataMember]
        public virtual Box Box { get; set; }
        [System.Runtime.Serialization.IgnoreDataMember]
        public virtual Gate Gate { get; set; }
        [System.Runtime.Serialization.IgnoreDataMember]
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [System.Runtime.Serialization.IgnoreDataMember]
        public virtual ICollection<TrackedItem> TrackedItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [System.Runtime.Serialization.IgnoreDataMember]
        public virtual ICollection<TrackHistory> TrackHistory { get; set; }
    }
}
